/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_ya_classloader_MyCustomClassLoader */

#ifndef _Included_me_ya_classloader_MyCustomClassLoader
#define _Included_me_ya_classloader_MyCustomClassLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_ya_classloader_MyCustomClassLoader
 * Method:    decryptJni
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_ya_classloader_MyCustomClassLoader_decryptJni
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
